name: application
hostname: qwe.loc
path: D:\WORK\projects\backend_for_site_on_react
virtualbox:
  memory: 4096
ip: 192.168.33.55
timezone: Europe/Kiev
db:
  user: vagrant
  password: vagrant
  name: php_course